/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllianceMenu: typeof import('./src/components/AllianceMenu.vue')['default']
    AmericanFootballGameCard: typeof import('./src/components/games/AmericanFootballGameCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseballGameCard: typeof import('./src/components/games/BaseballGameCard.vue')['default']
    BasketballGameCard: typeof import('./src/components/games/BasketballGameCard.vue')['default']
    CoinBalance: typeof import('./src/components/CoinBalance.vue')['default']
    CoinPurchaseDialog: typeof import('./src/components/CoinPurchaseDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ForumBoardManager: typeof import('./src/components/admin/ForumBoardManager.vue')['default']
    ForumList: typeof import('./src/components/ForumList.vue')['default']
    ForumNav: typeof import('./src/components/ForumNav.vue')['default']
    GameCard: typeof import('./src/components/games/GameCard.vue')['default']
    IceHockeyGameCard: typeof import('./src/components/games/IceHockeyGameCard.vue')['default']
    LegacyFooter: typeof import('./src/components/LegacyFooter.vue')['default']
    LegacyFrame: typeof import('./src/components/LegacyFrame.vue')['default']
    LegacyHeader: typeof import('./src/components/LegacyHeader.vue')['default']
    PostContent: typeof import('./src/components/PostContent.vue')['default']
    PredictGamesTable: typeof import('./src/components/PredictGamesTable.vue')['default']
    PredictionCard: typeof import('./src/components/PredictionCard.vue')['default']
    PredictionStatsBadge: typeof import('./src/components/games/PredictionStatsBadge.vue')['default']
    PrivacyPolicy: typeof import('./src/components/legal/PrivacyPolicy.vue')['default']
    PurchaseDialog: typeof import('./src/components/PurchaseDialog.vue')['default']
    ReplyList: typeof import('./src/components/ReplyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesPredictionRules: typeof import('./src/components/legal/SalesPredictionRules.vue')['default']
    SoccerGameCard: typeof import('./src/components/games/SoccerGameCard.vue')['default']
    TennisGameCard: typeof import('./src/components/games/TennisGameCard.vue')['default']
    TermsOfService: typeof import('./src/components/legal/TermsOfService.vue')['default']
    TipTapEditor: typeof import('./src/components/TipTapEditor.vue')['default']
    TipTapViewer: typeof import('./src/components/TipTapViewer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
